#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"

require "omniai/anthropic"
require "omniai/tools"

client = OmniAI::Anthropic::Client.new
logger = Logger.new($stdout)
logger.formatter = proc { |_, _, _, message| "[browser] #{message}\n" }

driver = OmniAI::Tools::Browser::WatirDriver.new

tools = [OmniAI::Tools::BrowserTool.new(driver:, logger:)]

puts "Type 'exit' or 'quit' to leave."

prompt = OmniAI::Chat::Prompt.build do |builder|
  builder.system <<~TEXT
    You are tasked with assisting a user in browsing the web.
  TEXT
end

loop do
  print "# "
  text = gets.strip
  break if %w[exit quit].include?(text)

  prompt.user(text)
  response = client.chat(prompt, stream: $stdout, tools:)
  prompt.assistant(response.text)
end
