#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"

require "omniai/openai"
require "omniai/tools"

require "watir"

browser = Watir::Browser.new(:chrome)

client = OmniAI::OpenAI::Client.new
logger = Logger.new($stdout)
logger.formatter = proc { |_, _, _, message| "[browser] #{message}\n" }

tools = [
  OmniAI::Tools::Browser::VisitTool,
  OmniAI::Tools::Browser::InspectTool,
  OmniAI::Tools::Browser::ButtonClickTool,
  OmniAI::Tools::Browser::LinkClickTool,
  OmniAI::Tools::Browser::TextFieldAreaSetTool,
].map { |klass| klass.new(browser:, logger:) }

puts "Type 'exit' or 'quit' to leave."

prompt = OmniAI::Chat::Prompt.build do |builder|
  builder.system <<~TEXT
    You are tasked with assisting a user in browsing the web.
  TEXT
end

loop do
  print "# "
  text = gets.strip
  break if %w[exit quit].include?(text)

  prompt.user(text)
  response = client.chat(prompt, stream: $stdout, tools:)
  prompt.assistant(response.text)
end
