#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"

require "omniai/openai"
require "omniai/tools"

require "sqlite3"

db = SQLite3::Database.new(":memory:")
driver = OmniAI::Tools::Database::SqliteDriver.new(db:)

client = OmniAI::OpenAI::Client.new
logger = Logger.new($stdout)
logger.formatter = proc { |_, _, _, message| "[database] #{message}\n" }

tools = [OmniAI::Tools::DatabaseTool.new(logger:, driver:)]

puts "Type 'exit' or 'quit' to leave."

prompt = OmniAI::Chat::Prompt.build do |builder|
  builder.system "Use tools to manage a Postgres database as requested."
end

loop do
  print "# "
  text = gets.strip
  break if %w[exit quit].include?(text)

  prompt.user(text)
  response = client.chat(prompt, stream: $stdout, tools:)
  prompt.assistant(response.text)
end
